#!/bin/bash

userresources=$HOME/.Xresources
usermodmap=$HOME/.Xmodmap
sysresources=/etc/X11/xinit/.Xresources
sysmodmap=/etc/X11/xinit/.Xmodmap

# merge in defaults and keymaps

for i in {$sysresources,$userresources}; do
    if [ -e $i ]; then
        xrdb -merge $i
    fi
done

for i in {$sysmodmap,$usermodmap}; do
    if [ -e $i ]; then
        xmodmap $i
    fi
done

# start some nice programs

if [ -d /etc/X11/xinit/xinitrc.d ] ; then
    for f in /etc/X11/xinit/xinitrc.d/?*.sh ; do
        [ -x "$f" ] && . "$f"
    done
    unset f
fi

# Fcitx variables
eval "$(dbus-launch --sh-syntax --exit-with-session)"
export GTK_IM_MODULE=fcitx
export QT_IM_MODULE=fcitx
export XMODIFIERS=@im=fcitx

# Fixes https://github.com/ValveSoftware/steam-for-linux/issues/1025
export STEAM_FRAME_FORCE_CLOSE=1

# Required for physlock
sessreg -a -l tty7 "$USER"

# Start window manager
compton -b --no-dock-shadow --no-dnd-shadow --vsync none --sw-opti --no-fading-openclose \
    --backend glx --glx-no-stencil --glx-use-copysubbuffermesa --glx-use-gpushader4 &
conky &
redshift -l 40.8:-73.9 -m randr -t 4200:1900 &
xbacklight -set 75 &
fcitx-autostart &
transmission-qt --minimized &
exec awesome

## Fallback
#xterm -geometry 80x50+494+51 &
#exec xterm -geometry 80x30+0+0 -name login

sessreg -d -l tty7 "$USER"

