#!/bin/bash
# Arch Linux-specific shell aliases

export AURDEST="$HOME/builds/pacaur"
export pacman_program='/usr/bin/pacaur'

pac() {
    if hash pacaur 2>/dev/null && hash pacmatic 2>/dev/null; then
        pacmatic "$@"
    elif hash pacaur 2>/dev/null; then
        pacaur "$@"
    elif hash pacmatic 2>/dev/null; then
        sudo pacmatic -E "$@"
    elif hash pacman 2>/dev/null; then
        sudo pacman "$@"
    fi
}

pacman_autoclean() {
    sudo paccache -r
    sudo paccache -ruk0
}

pacman_autoremove() {
    pac -Rn "$(pacman -Qqdt)" || printf "\n No unneeded packages. \n"
}

pacman_update_mirrorlist() {
    local file=/etc/pacman.d/mirrorlist.pacnew

    set -euo pipefail
    printf "\nGetting the latest HTTPS mirrorlist.\n"
    curl --silent -o /tmp/mirrorlist_new https://www.archlinux.org/mirrorlist/all/https/
    sed -i 's/^#Server/Server/' /tmp/mirrorlist_new
    printf "Ranking mirrors locally. This may take some time.\n"
    rankmirrors -n 6 /tmp/mirrorlist_new > /tmp/mirrorlist
    sudo cp /etc/pacman.d/mirrorlist /etc/pacman.d/mirrorlist.bak
    printf "Backed up old mirrorlist to /etc/pacman.d/mirrorlist.bak.\n"
    sudo cp /tmp/mirrorlist /etc/pacman.d/mirrorlist
    printf "New mirrorlist installed.\n"
    rm /tmp/mirrorlist_new /tmp/mirrorlist
    printf "Temporary files deleted.\n"
    [ -e "$file" ] && sudo rm "$file"
    printf "Deleted %s.\n" "$file"
    printf "Refreshing package lists.\n\n"
    pac -Syyu
}

